### ISSUE TITLE
ModuleNotFoundError: No module named 'spatial_correlation_sampler'

### ISSUE THREAD

**Issue by TechHalloman** [Anonymous0811/colorization#1]
RuntimeError: Error compiling objects for extension
2.2.0+cu121
Caching examples at: '/home/sos/Documents/colorization/gradio_cached_examples/15'
Caching example 1/1
sos                       Sun May 19 18:29:40 2024  535.171.04
[0] NVIDIA GeForce GTX 1060 6GB | 49°C,   8 % |   528 /  6144 MB | sos(107M) sos(65M) sos(7M) sos(206M) sos(137M)
Fps is 29.97002997002997
fps: 0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Using cache found in /home/sos/.cache/torch/hub/facebookresearch_dinov2_main
Traceback (most recent call last):
  File "/home/sos/Documents/colorization/app.py", line 421, in <module>
    demo = gr.Interface(
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/interface.py", line 518, in __init__
    self.render_examples()
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/interface.py", line 864, in render_examples
    self.examples_handler = Examples(
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/helpers.py", line 74, in create_examples
    examples_obj.create()
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/helpers.py", line 314, in create
    self._start_caching()
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/helpers.py", line 365, in _start_caching
    client_utils.synchronize_async(self.cache)
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio_client/utils.py", line 854, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/home/sos/anaconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/sos/anaconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/helpers.py", line 486, in cache
    prediction = await Context.root_block.process_api(
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/sos/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/sos/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/sos/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/sos/anaconda3/lib/python3.9/site-packages/gradio/utils.py", line 805, in wrapper
    response = f(*args, **kwargs)
  File "/home/sos/Documents/colorization/app.py", line 270, in inference
    network = XMem(config, args.model).cuda().eval()
  File "/home/sos/Documents/colorization/model/network.py", line 42, in __init__
    self.short_term_attn = LocalGatedPropagation(d_qk=64, # 256
  File "/home/sos/Documents/colorization/model/attention.py", line 764, in __init__
    from spatial_correlation_sampler import SpatialCorrelationSampler
ModuleNotFoundError: No module named 'spatial_correlation_sampler'

**Comment by yyang181** [comment]
Thanks for you attention or our work. This project is under construction and will be closed after merged to the main project. 

The error you post should be solved by compiling spatial_correlation_sampler package. I wrote a colab demo (https://colab.research.google.com/drive/1Nk4kEgHThWK2PihAnBUc_lyP7qTZZ2gm?usp=sharing) and would release it to the main project recently. 

Hope this helps.

**Comment by yyang181** [comment]
Note that current build for openxlab demo is unfinished. I cannot sync my code to build a demo. It's confusing and I will continue work on it. Anyway, hope the colab demo find you well.
